### ISSUE TITLE
Quotes API fixing Math.random() to a static value

### ISSUE THREAD

**Issue by prathap03** [Nareshram1/simbunewyear#3]
The implementation of random quotes API for STR quotes has been bugged out due to its implementation in Next.js. The API always return an static quote as the random logic is broken in the server side.

BUILD LOGS:

> simbunewyear@0.1.0 build
> next build

   ▲ Next.js 14.1.0

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
 ✓ Generating static pages (7/7)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size            First Load JS
┌ ○ /                                        961 B          85.1 kB
├ ○ /_not-found                      885 B            85 kB
├ ○ /api                                       0 B                0 B
└ ○ /api/str                                 0 B                0 B
+ First Load JS shared by all                          84.2 kB
  ├ chunks/69-971cc6ff58dfdad6.js               28.9 kB
  ├ chunks/fd9d1056-c50cb70e7323352b.js 53.4 kB
  └ other shared chunks (total)                      1.86 kB

○  (Static)  prerendered as static content

![image](https://github.com/Nareshram1/simbunewyear/assets/72980112/892d59ea-a086-4bcc-8151-736ea849bf27)

**Comment by Nareshram1** [comment]
Issue accepted, the team is notified and currently working on to fix it

**Comment by prathap03** [comment]
@Nareshram1 The issue has been fixed in the latest pull request. Thereby issue resolved

```typescript
//Crucial Line for Dynamic API Routes
export const dynamic = 'force-dynamic'
```

![image](https://github.com/Nareshram1/simbunewyear/assets/72980112/d7b56061-3126-429e-b49e-2df6c50ee62c)
